"""
Django settings for SmartHire_Project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&+i(9rxeuk-saet)3r8fmz=*jjip7+im3&48=trafro#gld)$i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'candidate',
    'employer',
    'crispy_forms',
    'crispy_bootstrap4',
    'django_htmx',
    'channels',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'SmartHire_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartHire_Project.wsgi.application'


# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Add this
CELERY_BROKER_HEARTBEAT = 10  # Send heartbeat every 10s
CELERY_BROKER_CONNECTION_MAX_RETRIES = None  # Retry indefinitely
CELERY_TASK_TRACK_STARTED = True

# Ensure ASGI_APPLICATION is set for Channels
ASGI_APPLICATION = 'SmartHire_Project.asgi.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],  # Default Redis port
        },
    },
}

# SESSION_ENGINE = "mongoengine.django.sessions"
# SESSION_ENGINE = 'mongoengine.django.sessions'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

SESSION_CACHE_ALIAS = 'default'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.dummy',  # Use a dummy database backend
#     }
# }

# DATABASES = {}

AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.MongoDBBackend',  # Your custom authentication
]





import pymongo
import urllib.parse

# # Your MongoDB credentials
# username = "smarthire"  # Replace with your actual username
# # password = "Devil@ai075907"  # Replace with your actual password
# password = "Devilai075907"  # Replace with your actual password

# Encode special characters
# encoded_username = urllib.parse.quote_plus(username)
# encoded_password = urllib.parse.quote_plus(password)
# MONGO_URI = f"mongodb+srv://{encoded_username}:{encoded_password}@cluster.mongodb.net/?retryWrites=true&w=majority"


# MongoDB connection
 
import pymongo
 
# MONGO_URI = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&readPreference=primaryPreferred&appName=SmartHireCluster"

# MONGO_URI = "mongodb+srv://smarthireuser:NEW_PASSWORD@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&readPreference=primary&appName=SmartHireCluster"

# from pymongo.mongo_client import MongoClient
# from pymongo.server_api import ServerApi

# uri = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster"

# # Create a new client and connect to the server
# client = MongoClient(uri, server_api=ServerApi('1'))

# # Send a ping to confirm a successful connection
# try:
#     client.admin.command('ping')
#     print("Pinged your deployment. You successfully connected to MongoDB!")
# except Exception as e:
#     print(e)
# MongoDB connection 
MONGO_URI = "mongodb+srv://smarthireu1:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster"
# MONGO_URI = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster&readPreference=secondaryPreferred"
# MONGO_URI = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster&readPreference=secondaryPreferred&connectTimeoutMS=30000&serverSelectionTimeoutMS=5000"
# MONGO_URI = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster&readPreference=secondaryPreferred&connectTimeoutMS=30000&serverSelectionTimeoutMS=5000&minPoolSize=5&maxPoolSize=50"
# MONGO_URI = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster&readPreference=primary&connectTimeoutMS=30000&serverSelectionTimeoutMS=5000&minPoolSize=5&maxPoolSize=50"
# MONGO_URI = "mongodb+srv://smarthireuser:Devilai075907@smarthirecluster.ldebi.mongodb.net/?retryWrites=true&w=majority&appName=SmartHireCluster&readPreference=primary"


MONGO_CLIENT = pymongo.MongoClient(
    MONGO_URI,
    maxPoolSize=50,  # Maximum number of connections
    minPoolSize=5,   # Minimum number of connections
    serverSelectionTimeoutMS=5000,  # Reduce timeout to fail fast
    connectTimeoutMS=30000  # Increase connection timeout
)

# MONGO_CLIENT = pymongo.MongoClient(MONGO_URI)
MONGO_DB = MONGO_CLIENT['smarthireDB']  # Database name
USERS_COLLECTION = MONGO_DB['users']  # Collection name
 
# db = client["job_postings_db"]
jobs_collection = MONGO_DB["jobs"]





# Custom User model
# AUTH_USER_MODEL = 'accounts.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),           # Project-level static directory
    # os.path.join(BASE_DIR, 'candidate/static'), # Candidate app static directory
]

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/index/'

# File storage (adjust as needed)
# MEDIA_ROOT = os.path.join(BASE_DIR, 'resumes')
# MEDIA_URL = '/resumes/'

import os

# Media files (for user-uploaded files like resumes)
MEDIA_URL = '/media/'  # This is the URL prefix to serve media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # This is where uploaded files will be stored
