# Generated by Django 5.1.6 on 2025-06-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_app.jobdescription')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('is_followup', models.BooleanField(default=False)),
                ('followup_depth', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_app.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('detected_pause', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('completeness_score', models.IntegerField(blank=True, default=None, null=True)),
                ('relevance_score', models.IntegerField(blank=True, default=None, null=True)),
                ('clarity_score', models.IntegerField(blank=True, default=None, null=True)),
                ('plagiarized', models.BooleanField(blank=True, default=None, null=True)),
                ('plagiarism_source', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview_app.question')),
            ],
        ),
    ]
